### ISSUE TITLE
Chapter 2 Negative Gradient

### ISSUE THREAD

**Issue by SPDA36** [rasbt/machine-learning-book#141]
Page 38 says we update weights and biases by adding the parameter to the negative gradient * learning rate.  However, in the Adaline code sections, pages 40 and 49, no negative gradient is used.  For example, page 49, `self.w_ += self.eta * 2.0 * xi * (error)`.

**Comment by rasbt** [comment]
Thanks for the note, and that's a good point. At first glance it may look wrong. But we have ` errors = (y - output)`, and that's the negative gradient. 

That's because `-(y - output)` is the gradient as shown at the bottom of pg 38. And `-1 * -(y - output)` simplifies to `(y - output)`.
 
<img width="579" alt="Screenshot 2023-08-17 at 11 59 26 AM" src="https://github.com/rasbt/machine-learning-book/assets/5618407/c18067c4-4de4-43d8-a173-d8b8b16341fa">

**Comment by SPDA36** [comment]
The obvious was staring at me and I still managed to overlook it. Thanks for the clarification!
